const emojiList = {
    srcs: [
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f603.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f618.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f602.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f633.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f60d.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f44f.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f44d.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f44e.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f601.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f609.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f620.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f61e.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f625.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f62d.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f61d.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f621.svg',
        // 'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/2764.svg"',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f494.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f623.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f614.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f604.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f637.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f61a.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f613.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f60a.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f622.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f61c.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f628.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f630.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f632.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f60f.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f631.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f62a.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f616.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f60c.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f612.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f47b.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f385.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f467.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f466.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f469.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f468.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f436.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f431.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f44a.svg',
        // 'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/270c.svg"',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f4aa.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f446.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f447.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f449.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f448.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f44c.svg',
        'https://gold-cdn.xitu.io/asset/twemoji/2.6.0/svg/1f4a9.svg'
    ],
    alts: ['😜', '😨', '😰', '😲', '😏', '😱', '😪', '😖', '😌', '😒', '👻', '🎅', '👧', '👦', '👩', '👨', '🐶', '🐱', '👊', '✊', '✌', '💪', '👆', '👇', '👉', '👈', '👌', '💩']

}

export default emojiList